### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by svdm-artix** [jpochyla/psst#170] opened 2021-09-07 02:36 UTC
Hello! I am interested in creating my first flatpak project and would like to start with psst. One problem however is that there is no versioning scheme yet. When is the first version of psst expected to be released?

**Comment by jpochyla** [comment] 2021-09-14 15:33
Thanks! There is #141 open with this, could you take a look at it and chime in? There's no versioning yet, Psst is in alpha, soonish we should prepare some milestones and release stable-ish snapshots.

**Comment by jpochyla** [comment] 2021-09-14 15:33
Also, I'll close this as a duplicate of #16, if you don't mind.

**Closed by jpochyla** 2021-09-14 15:33 UTC

**Comment by Peque** [comment] 2024-09-25 13:22
Cross-referencing https://github.com/jpochyla/psst/issues/530, which suggests the addition of a Flatpak package as well as the distribution of the package via Flathub for easier/wider adoption. :blush:
