### ISSUE TITLE
No audio on playback

### ISSUE THREAD

**Issue by omnituensaeternum** [jpochyla/psst#163] opened 2021-08-31 23:03 UTC
```
[2021-08-31T23:01:21Z INFO  psst_gui::data::config] loading config: "/home/User/.config/Psst/config.json"
[2021-08-31T23:01:21Z INFO  psst_core::cache] using cache: "/home/User/.cache/Psst"
[2021-08-31T23:01:21Z INFO  psst_gui::data::config] saved config: "/home/User/.config/Psst/config.json"
[2021-08-31T23:01:21Z INFO  psst_core::access_token] access token expired, requesting
[2021-08-31T23:01:29Z INFO  psst_core::access_token] access token expired, requesting
[2021-08-31T23:01:29Z INFO  psst_core::audio_file] blocked at 7871328
[2021-08-31T23:01:29Z INFO  psst_core::audio_file] blocked at 7904096
[2021-08-31T23:01:29Z INFO  psst_core::audio_file] blocked at 7910408
[2021-08-31T23:01:29Z INFO  psst_core::audio_file] blocked at 7926792
[2021-08-31T23:01:29Z INFO  psst_core::audio_player] starting playback
[2021-08-31T23:01:29Z INFO  psst_gui::controller::playback] playing
[2021-08-31T23:01:40Z INFO  psst_core::audio_player] pausing playback
[2021-08-31T23:01:41Z INFO  psst_core::audio_player] resuming playback
[2021-08-31T23:01:45Z INFO  psst_core::audio_file] blocked at 9059660
[2021-08-31T23:01:46Z INFO  psst_core::audio_file] blocked at 9076044
[2021-08-31T23:01:46Z INFO  psst_core::audio_file] blocked at 9092428
[2021-08-31T23:01:46Z INFO  psst_core::audio_file] blocked at 9098740
[2021-08-31T23:01:46Z INFO  psst_core::audio_file] blocked at 9115124
[2021-08-31T23:01:46Z INFO  psst_core::audio_player] starting playback
[2021-08-31T23:01:46Z ERROR psst_core::audio_output] failed to start device: generic
[2021-08-31T23:01:46Z INFO  psst_gui::controller::playback] playing
[2021-08-31T23:02:02Z INFO  psst_core::audio_player] pausing playback
```
Recently Updated my system and preformed a restart.
I tried reinstalling, and I got the same results.

**Comment by jpochyla** [comment] 2021-09-01 15:23
What OS are you on?

**Comment by jacksongoode** [comment] 2021-09-01 16:45
Was debugging this issue last night (Fedora 34, pipewire). I think it's related to the fact that the buffersize for psst is too low (at least compared to other media players). 

Here is an output of `pw-top`:

```
QUANT   RATE    WAIT     BUSY    W/Q   B/Q   ERR
256     48000   253.2µs  60.6µs  0.05  0.01  0    alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH035200SQJKLTAA-00.analog-stereo
256     48000   100.8µs  13.9µs  0.02  0.00  0    + psst-gui
3969    44100   133.7µs  58.9µs  0.03  0.01  0    + Rhythmbox
```

Where, for some reason, psst is taking a very small buffer of 256 compared to other audio applications taking a generous amount more.

**Comment by jpochyla** [comment] 2021-09-01 17:31
@jacksongoode [miniaudio-tuning](https://github.com/jpochyla/psst/tree/miniaudio-tuning) branch should increase the buffer size, can you check it out? From the output it also seems that miniaudio is using the alsa backend, correct?

**Comment by jacksongoode** [comment] 2021-09-01 17:58
@jpochyla Tried the new branch, it does increase the buffer size (now reporting 1440) but it's still running into the same issue. So it may be more of an issue with `miniaudio` perhaps as the conversation at #138 has lead me to believe. It seems replacing `miniaudio` with `cpal` fixed it for me (in pw-top the application is now reported as `+ PipeWire ALSA [psst-gui]`).

**Comment by etrigan63** [comment] 2021-09-05 20:25
I can confirm this. No audio playback in pipewire. I don't know how to switch it to `cpal` from `miniaudio`, however.

**Comment by jacksongoode** [comment] 2021-09-15 00:58
> I can confirm this. No audio playback in pipewire. I don't know how to switch it to `cpal` from `miniaudio`, however.

If you build the app with [this fork's branch](https://github.com/H-M-H/psst/tree/cpal), you should be good to go!

**Comment by jacksongoode** [comment] 2021-09-15 07:23
I wanted to follow up with this as the latest version of pipewire improved on the buffer/quantum configurations and I believe it resolved the issues here. Currently on version 0.3.35, would love to know if anyone else can confirm this behavior?

**Comment by jpochyla** [comment] 2021-09-15 07:52
> I wanted to follow up with this as the latest version of pipewire improved on the buffer/quantum configurations and I believe it resolved the issues here. Currently on version 0.3.35, would love to know if anyone else can confirm this behavior?

Thanks!

> However, I am still getting around 6 "blocked" messages every time a new song is played:

`blocked` means blocked on network, it is unrelated to audio output and will always be there when loading/preloading a track.

**Comment by H-M-H** [comment] 2021-09-29 10:09
I am on pipewire 0.3.37 and playback is working again.

**Comment by naufik** [comment] 2021-10-05 08:25
I am receiving no audio output with no pipewire and just pure pulseaudio when building from `master`.

```
~ % pulseaudio --version
pulseaudio 14.2-rebootstrapped
```

`pavucontrol` does not seem to detect audio coming from psst either. However the `cpal` patch in the fork works.

**Comment by jpochyla** [comment] 2021-12-24 13:18
Closing because we've migrated to `cpal`, causing other problems, but most probably fixing this issue.

**Closed by jpochyla** 2021-12-24 13:18 UTC
Labels: bug, linux
