### ISSUE TITLE
MPRIS DBus missing field xesam:albumArtist

### ISSUE THREAD

**Issue by YodaEmbedding** [jpochyla/psst#425] opened 2023-05-28 04:46 UTC
```python
from pprint import pprint
from mpris2 import Player

uri = "org.mpris.MediaPlayer2.psst"
player = Player(dbus_interface_info={"dbus_uri": uri})

pprint(player.Metadata)
```

Outputs:
```
{dbus.String('mpris:artUrl'): dbus.String('https://i.scdn.co/image/ab67616d0000b2731f829ea9c2c7ffcec1a3c857', variant_level=1),
 dbus.String('mpris:length'): dbus.Int64(152560000, variant_level=1),
 dbus.String('mpris:trackid'): dbus.ObjectPath('/', variant_level=1),
 dbus.String('xesam:album'): dbus.String('Unknown', variant_level=1),
 dbus.String('xesam:artist'): dbus.Array([dbus.String('Alice In Chains')], signature=dbus.Signature('s'), variant_level=1),
 dbus.String('xesam:title'): dbus.String('We Die Young', variant_level=1)}
```

**Comment by Insprill** [comment] 2023-05-28 04:47
Duplicate of #368.

**Closed by Insprill** 2023-05-28 04:47 UTC
Labels: bug, duplicate
