### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#494] opened 2024-07-08 19:46 UTC
All new projects use main as the default branch. 

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch

However, only @jpochyla can do this :)

**Comment by fougner** [comment] 2024-07-15 07:57
any reason why you open a duplicate of https://github.com/jpochyla/psst/issues/418 which you opened a year ago? if not maybe you can close this one

**Comment by jacksongoode** [comment] 2024-07-15 12:12
Not a lot of historical knowledge here!

**Closed** 2024-07-16 07:34 UTC
