### ISSUE TITLE
Running without opening the terminal window

### ISSUE THREAD

**Issue by sintezcs** [jpochyla/psst#106] opened 2021-08-18 09:55 UTC
Hi guys, thank you for a great product! I have a question, is it possible to not show the terminal window when running an app in Mac OS?

**Comment by timgws** [comment] 2021-08-18 10:00
Yeah, it's definitely possible. I think we will need to build an app bundle, though.

https://github.com/burtonageo/cargo-bundle, https://developer.apple.com/go/?id=bundle-structure

**Comment by sintezcs** [comment] 2021-08-18 10:03
@timgws cool, thank you! I'll try this out

**Comment by jpochyla** [comment] 2021-08-18 10:34
Closing as duplicate of #82, it's in the works :)

**Closed by jpochyla** 2021-08-18 10:34 UTC
