### ISSUE TITLE
[?Bug Report/Feature Request?] Changing audio device on windows doesn’t apply on on going playback session

### ISSUE THREAD

**Issue by TomBonnot** [jpochyla/psst#419] opened 2023-05-17 16:13 UTC
**Describe the bug**
Changing default output device onto windows settings doesn’t apply for Psst

**To Reproduce**
Two different audio device : Headphones and Speakers, Open Psst when being on Headphones default audio, start playback, then change to Speakers, audio will stay on Headphones

**Expected behavior**
In my above lore, the playback from Psst should go into the Speakers

**Environment**
 - OS: Windows 11
 - Version: 22H2

**Additional context**
[Feature Request] 
This problem could be fixed by adding a default Output directly into Psst, this way you don’t have to detect main output and auto switching to it with the system, but the user will have to setup its own default audio output for playback (in my situation I would like to have it into my speakers and the rest into my headphones). 

This isn’t a top priority point but could be a nice feature. 

Anyway, a huge thanks for your work and this helpful lightweight software.

**Comment by Insprill** [comment] 2023-05-17 16:18
Duplicate of #215

**Closed as not planned** 2023-05-17 16:18 UTC
Labels: bug, duplicate
