### ISSUE TITLE
Arch - Can't open

### ISSUE THREAD

**Issue by FuzzyMistborn** [jpochyla/psst#274] opened 2022-01-26 14:11 UTC
**Describe the bug**

I tried updating Psst to the latest on Arch (installed via AUR) and now I can't open Psst.  I see the icon flash in my taskbar for a second but then it goes away.

**To Reproduce**
Steps to reproduce the behavior.

Install via AUR.  Try to open.  Doesn't open.

**Expected behavior**
See above.

**Screenshots**

**Environment**
 - OS: Arch
 - Version: latest?  Built off the psst-git 

**Additional context**

Happy to provide logs or anything else that would be of use, just not sure where to look.  Know Arch isn't technically supported but wondering if there's some other issue I may be missing.

**Comment by jpochyla** [comment] 2022-01-26 15:44
Can you send run psst from a terminal and send the output?

**Comment by FuzzyMistborn** [comment] 2022-01-26 16:05
`psst` isn't working in the terminal.

**Comment by jpochyla** [comment] 2022-01-26 16:12
psst-gui then?

**Comment by FuzzyMistborn** [comment] 2022-01-26 16:23
That worked.
```
$ psst-gui
[2022-01-26T16:22:23Z INFO  psst_gui::data::config] loading config: "/home/fuzzy/config/Psst/config.json"
[2022-01-26T16:22:23Z ERROR psst_gui::webapi::client] failed to read local tracks: No such file or directory (os error 2)
[2022-01-26T16:22:23Z INFO  psst_core::audio::output] using audio device: "default"
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AudioOutputError(DeviceNotAvailable)', psst-gui/src/controller/playback.rs:53:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lemon-sh** [comment] 2022-02-27 20:23
I am having the same issue, running with pipewire

**Comment by lemon-sh** [comment] 2022-02-27 20:28
Update: fixed by installing `pipewire-alsa` and running normally.
Still, I think psst should use the PulseAudio frontend when running with pipewire.

**Comment by Insprill** [comment] 2023-01-09 21:28
Duplicate of #230

**Closed by Insprill** 2023-01-09 21:28 UTC
Labels: bug, duplicate, linux
