### ISSUE TITLE
Crashes on Startup Arch Linux

### ISSUE THREAD

**Issue by hughesjs** [jpochyla/psst#353] opened 2022-10-22 18:51 UTC
**Describe the bug**
Start `psst-gui` and login. App immediately crashes.

STD_ERR reports (with `RUST_BACKTRACE=full`):

>  !  ~  RUST_BACKTRACE=full psst-gui                                                                                 Sat 22 Oct 2022 19:48:17 BST
> [2022-10-22T18:49:35Z INFO  psst_gui::data::config] loading config: "/home/james/.config/Psst/config.json"
> [2022-10-22T18:49:35Z INFO  psst_gui::webapi::local] parsing local tracks: "/home/james/.config/spotify/Users/tniu738flenbq0ormrdd3eaa3-user/local-files.bnk"
> [2022-10-22T18:49:35Z INFO  psst_core::audio::output::cpal] using audio device: "default"
> ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AudioOutputError(DeviceNotAvailable)', psst-gui/src/controller/playback.rs:53:49
> stack backtrace:
>    0:     0x55dcbb251bd1 - <unknown>
>    1:     0x55dcbaff001c - <unknown>
>    2:     0x55dcbb22bdb4 - <unknown>
>    3:     0x55dcbb252946 - <unknown>
>    4:     0x55dcbb2539d8 - <unknown>
>    5:     0x55dcbb2534b2 - <unknown>
>    6:     0x55dcbb253426 - <unknown>
>    7:     0x55dcbb2533e2 - <unknown>
>    8:     0x55dcbaa9aa02 - <unknown>
>    9:     0x55dcbaa9ac82 - <unknown>
>   10:     0x55dcbabc53ed - <unknown>
>   11:     0x55dcbad913bf - <unknown>
>   12:     0x55dcbaea7dff - <unknown>
>   13:     0x55dcbad913bf - <unknown>
>   14:     0x55dcbab01acd - <unknown>
>   15:     0x55dcbad913bf - <unknown>
>   16:     0x55dcbabc0a38 - <unknown>
>   17:     0x55dcbad913bf - <unknown>
>   18:     0x55dcbad912bd - <unknown>
>   19:     0x55dcbae12dcb - <unknown>
>   20:     0x55dcbae11836 - <unknown>
>   21:     0x55dcbad08ae9 - <unknown>
>   22:     0x55dcbad045bb - <unknown>
>   23:     0x55dcbaeb9b8c - <unknown>
>   24:     0x55dcbad06d1a - <unknown>
>   25:     0x55dcbafc6a5e - <unknown>
>   26:     0x55dcbaca1dc3 - <unknown>
>   27:     0x55dcbafd7506 - <unknown>
>   28:     0x7f2663d51290 - <unknown>
>   29:     0x7f2663d5134a - __libc_start_main
>   30:     0x55dcbaab3c75 - <unknown>
>   31:                0x0 - <unknown>

**To Reproduce**
Start `psst-gui` and log-in

**Expected behavior**
It logs in and gui launches.

**Screenshots**
N/A

**Environment**
 - OS: Arch Linux
 - Version: `5.19.13-arch1-g14-3`
 - DM: Sway

**Additional context**
I'm using PulseAudio for my sound stack

**Comment by hughesjs** [comment] 2022-10-22 18:59
This seems relevant: https://github.com/RustAudio/rodio/issues/267

And installing this seems to fix the issue but this definitely feels like a workaround, not a fix: https://archlinux.org/packages/extra/x86_64/pulseaudio-als

**Comment by bemug** [comment] 2022-11-08 23:03
I confirm installing pulseaudio-alsa works.

**Comment by Insprill** [comment] 2023-01-09 21:29
Duplicate of #230

**Closed by Insprill** 2023-01-09 21:29 UTC
Labels: bug, duplicate

**Comment by kepi** [comment] 2024-03-22 16:05
Just for those who stumble here looking for solution and using pipewire, `pipewire-alsa` instead of pulseaudio one works too.
