### ISSUE TITLE
Clicking the "next track" button causes the song you were listening to "blip" before the next track starts.

### ISSUE THREAD

**Issue by winteriscariot** [jpochyla/psst#553] opened 2024-11-04 18:07 UTC
This is a little weird to describe, but basically whenever I click the "Next track" button the current song stops playing while Psst loads the next song (which takes about 1s or less, no real problems there).

the issue is that after that brief loading pause, there's a like fraction-of-a-second spurt of audio from the previous track, before the next track starts.

this doesn't occur when a song ends and it moves onto the next song in the list, only when clicking "Next track"

edit: it also occurs when selecting a new song (simply clicking on a song in your library to play, while a song is playing)

Arch Linux, psst-git r561.0292319-1

**Comment by SO9010** [comment] 2024-11-05 12:31
Duplicate of #251

**Closed** 2024-11-05 19:38 UTC
Labels: bug
