### ISSUE TITLE
[Linux] debian/ubuntu package naming conflict

### ISSUE THREAD

**Issue by ChrisLauinger77** [jpochyla/psst#473] opened 2024-05-18 13:46 UTC
**Describe the bug**
debian package naming conflict
https://packages.debian.org/trixie/psst

I am not an ubuntu user but they might have the same problem
https://launchpad.net/ubuntu/+source/psst

**To Reproduce**
install the deb from here and then apt update && apt upgrade

**Expected behavior**
debian should not replace the package with the one from the repo

**Environment**
 - OS: debian
 - Version: any

**Additional context**
maybe rename the package to psst-gui or something ?

**Comment by Insprill** [comment] 2024-05-18 16:49
Duplicate of #391

**Closed** 2024-05-18 16:49 UTC
Labels: bug
