### ISSUE TITLE
Open spotify link in Psst

### ISSUE THREAD

**Issue by gagarine** [jpochyla/psst#323] opened 2022-08-14 12:41 UTC
Would it be possible that link in the form  of  https://open.spotify.com/track/XXXXXX send by email, whatsapp or in the browser be automatically open int Psst?

**Comment by gagarine** [comment] 2022-08-14 12:51
I tried to use https://github.com/johnste/finicky , Psst seem to receive the link (focus switch) but then is not able to open it.

**Comment by jpochyla** [comment] 2022-08-15 14:24
Duplicate of #159

**Closed** 2022-08-15 14:25 UTC
