### ISSUE TITLE
Hangs after connection is lost

### ISSUE THREAD

**Issue by thibautvdv** [jpochyla/psst#10] opened 2021-01-04 15:27 UTC
After connection is lost and reset, the player hangs (running with WiFi).
This is the output:
>[2021-01-04T15:21:39Z ERROR psst_gui::delegate] connection error: IoError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })
[2021-01-04T15:21:42Z INFO  psst_gui::delegate] session connected
>[2021-01-04T15:22:07Z INFO  psst_core::stream_storage] blocked at 8992924
[2021-01-04T15:22:07Z INFO  psst_core::stream_storage] blocked at 7408684
[2021-01-04T15:22:07Z INFO  psst_core::stream_storage] blocked at 7447668
[2021-01-04T15:22:07Z INFO  psst_core::stream_storage] blocked at 6179592
[2021-01-04T15:22:07Z INFO  psst_core::audio_player] stale open result received, ignoring

After this, nothing happens, unless selecting a new song.

**Comment by thibautvdv** [comment] 2021-01-04 16:08
This now seems to happen after every song. I recall having the same issue when I was using spotify-tui and I think the problem was the client couldn't handle a connection reset (https://github.com/Rigellute/spotify-tui/issues/178 and https://github.com/librespot-org/librespot/issues/134).

**Comment by jpochyla** [comment] 2021-01-04 16:20
I think this is a bug unrelated to Spotify connection, caused by d136d3bd. I'm on it!

**Comment by jpochyla** [comment] 2021-01-04 16:30
Should be fixed in da88499a. Leaving this issue open as network resiliency is on the roadmap.

**Comment by thibautvdv** [comment] 2021-01-04 18:18
It has been working now with no issues for 2 hours! :tada: Nice work and thanks for the fast fixes!

**Closed** 2021-01-04 18:43 UTC

**Comment by kirillrogovoy** [comment] 2022-08-28 11:39
I have this problem on macOS 12.3.1 and the latest Psst.

Only that in my case, it hangs until I restart the app. I can still browse the catalog, but the playback is dead.

**Comment by conartist6** [comment] 2022-12-31 20:01
All issues related to this problem are "closed as completed" which seems misleading, and makes it more difficult to find https://github.com/librespot-org/librespot/discussions/609. Once a user does find it they need to read the entire thread to figure out if the problem still exists. It definitely seems to.
