### ISSUE TITLE
Hide password during login

### ISSUE THREAD

**Issue by derwana** [jpochyla/psst#444] opened 2023-11-07 07:46 UTC
**Is your feature request related to a problem? Please describe.**
At the moment the password is shown as clear text during input on login. I really do not like to see my or any other peoples passwords in clear.

**Describe the solution you'd like**
The password should be only visible as dots or asterisks.

**Describe alternatives you've considered**
In my opinion the password should never ever be visible in clear, except there is an eye-button to have a look at it.

**Comment by Insprill** [comment] 2023-11-07 15:13
Duplicate of #45. This is a technical limitation in Druid that we can't do anything about.

**Closed** 2023-11-07 15:13 UTC
Labels: duplicate
