### ISSUE TITLE
Super high cpu usage

### ISSUE THREAD

**Issue by erikc96** [jpochyla/psst#142] opened 2021-08-23 15:44 UTC
I just caught Psst using 90% of my cpu on an m1 mac. Is this not typical?

**Comment by jpochyla** [comment] 2021-08-23 19:05
No it is not typical. Do you have a reproducible example?

**Comment by Kethku** [comment] 2021-08-24 20:49
Did you build it in release mode?

**Comment by Kethku** [comment] 2021-08-24 20:51
On windows, psst uses .1% of my cpu while playing. In contrast, spotify sticks right around 1.7% to 2%. I definitely do not incounter 90% usage

**Comment by ceifa** [comment] 2021-09-01 19:08
30% CPU running version e6e3cfa from snap:

![image](https://user-images.githubusercontent.com/26205666/131729291-82dd0c8d-9943-44ec-99c1-7ee2696e5276.png)


> @erikc96 could you run a profiler on the app when it is using all that cpu to get an estimate of where that cpu time is going?

How do I do that?

**Comment by jpochyla** [comment] 2021-09-01 19:59
@ceifa can you try the latest master? Ambient playback CPU usage should be much lower.

**Comment by ceifa** [comment] 2021-09-01 20:44
On current master version running the release mode:
![image](https://user-images.githubusercontent.com/26205666/131741583-9ac9fd61-82c0-48c0-b22b-8976ee68320f.png)

But now "pulseaudio" takes a lot of CPU...

Running spotify:
![image](https://user-images.githubusercontent.com/26205666/131742359-8c07fb6c-b449-4e97-a0d2-83902d9a5001.png)

**Comment by pablodz** [comment] 2021-09-01 20:51
> But now "pulseaudio" takes a lot of CPU...

Did you read about pipewire? it handles better CPU usage than pulseaudio.

**Comment by ceifa** [comment] 2021-09-06 18:34
> Did you read about pipewire? it handles better CPU usage than pulseaudio.
Never did, but I will take a look, thanks for the hint!

**Comment by pablodz** [comment] 2021-09-08 16:00
> > Did you read about pipewire? it handles better CPU usage than pulseaudio.
> 
> Never did, but I will take a look, thanks for the hint!

Yes, check the graph in p10 https://elinux.org/images/5/55/Pipewire-slides.pdf

**Comment by jpochyla** [comment] 2021-09-14 15:47
High PulseAudio CPU usage is caused by the small buffer size we use now, will be solved when we switch to `cpal` for the audio output. Anyway that seems unrelated to the original issue, so let's close this, if you don't mind!

**Closed by jpochyla** 2021-09-14 15:47 UTC
