### ISSUE TITLE
Pulseaudio without ALSA

### ISSUE THREAD

**Issue by AarizYT** [jpochyla/psst#245] opened 2022-01-03 18:12 UTC
**Is your feature request related to a problem? Please describe.**
I can't use psst on Termux PRoot container (Arch Linux ARM64) as ALSA doesn't work. (Note: This is a problem with Termux, only Pulseaudio is supported) 

Here is the log:-
[Log.txt](https://github.com/jpochyla/psst/files/7803343/Log.txt)

**Describe the solution you'd like**
It would be great if I could use Pulseaudio directly. I have compiled librespot with pulseaudio backend and it worked. 

**Describe alternatives you've considered**
I have tried to get ALSA to work but it doesn't seem like it's possible. Pulseaudio is the only option I have.

**Additional context**
Environment: Arch Linux ARM64 running in a PRoot container on Termux on Android

**Comment by Insprill** [comment] 2023-01-09 21:28
Duplicate of #230

**Closed by Insprill** 2023-01-09 21:28 UTC
Labels: enhancement, linux, lowprio
